In [11]:
import numpy as np
import statistics as s
import pandas as pd
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

In [12]:
df=pd.read_csv("C:\\Users\\Aman\\Desktop\\battery_charger.csv")

In [13]:
df.head()

inp1  inp2  out
0   0.0   0.0  4.0
1  30.0   1.0  4.0
2  37.0   0.2  4.0
3  40.0   0.0  3.0
4  40.0   1.0  2.0

In [14]:
z=df[['inp1','inp2']]

In [23]:
lr = LinearRegression()
lr

LinearRegression()

In [26]:
lr.fit(z,df[['out']])

LinearRegression()

In [27]:
lr

LinearRegression()

In [32]:
n=float(input("Enter input1:-"))
x=float(input("Enter input2:-"))
T = [[n,x]]
Yhat=lr.predict(T)
Yhat

Enter input1:-41.2
Enter input2:-.7


array([[1.39025088]])

In [33]:
lr.intercept_

array([4.66504615])

In [34]:
lr.coef_

array([[-0.08092162,  0.0845361 ]])

In [37]:
Yhat=lr.predict(z)
mse= mean_squared_error(df[['out']],Yhat)
print("The MSE  and pridicted value is :",mse)

The MSE  and pridicted value is : 0.8412891547113011


In [38]:
lr.score(z,df[['out']])

0.71816259198405